use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Kalanhall/Specs.git'

target 'CustomLoading_Example' do
  pod 'CustomLoading', :path => '../'

  target 'CustomLoading_Tests' do
    inherit! :search_paths

    
  end
end
